"""organization settings

Revision ID: cfda4b80984f
Revises: 4e0b8dc0dd8f
Create Date: 2026-09-27 20:06:46.481359+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cfda4b80984f"
down_revision: str | None = "4e0b8dc0dd8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CHECKS = [
    ("idno_format", "idno IS NULL OR idno ~ '^[0-9]{13}$'"),
    ("vat_code_format", "vat_code IS NULL OR vat_code ~ '^[0-9]{7}$'"),
    ("iban_format", "iban IS NULL OR iban ~ '^MD[0-9]{2}[A-Z0-9]{20}$'"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organizations", sa.Column("full_name", sa.String(length=500), nullable=True))
    op.add_column("organizations", sa.Column("vat_code", sa.String(length=7), nullable=True))
    op.add_column("organizations", sa.Column("legal_address", sa.String(length=500), nullable=True))
    op.add_column("organizations", sa.Column("phone", sa.String(length=32), nullable=True))
    op.add_column("organizations", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column("organizations", sa.Column("website", sa.String(length=255), nullable=True))
    op.add_column("organizations", sa.Column("director_name", sa.String(length=255), nullable=True))
    op.add_column("organizations", sa.Column("bank_name", sa.String(length=100), nullable=True))
    op.add_column("organizations", sa.Column("iban", sa.String(length=24), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate nu detectează constrângerile CHECK.
    for name, condition in _CHECKS:
        op.create_check_constraint(op.f(f"ck_organizations_{name}"), "organizations", condition)


def downgrade() -> None:
    for name, _ in _CHECKS:
        op.drop_constraint(op.f(f"ck_organizations_{name}"), "organizations", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "iban")
    op.drop_column("organizations", "bank_name")
    op.drop_column("organizations", "director_name")
    op.drop_column("organizations", "website")
    op.drop_column("organizations", "email")
    op.drop_column("organizations", "phone")
    op.drop_column("organizations", "legal_address")
    op.drop_column("organizations", "vat_code")
    op.drop_column("organizations", "full_name")
    # ### end Alembic commands ###
