"""clients, bank accounts, contacts, assignments

Revision ID: 75efc605cc5b
Revises: f13e14e80bfd
Create Date: 2026-09-27 15:55:07.469769+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "75efc605cc5b"
down_revision: str | None = "f13e14e80bfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=500), nullable=True),
        sa.Column("idno", sa.String(length=13), nullable=False),
        sa.Column(
            "legal_form",
            sa.Enum(
                "SRL",
                "SA",
                "II",
                "GT",
                "ONG",
                name="legal_form",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("vat_payer", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("vat_code", sa.String(length=7), nullable=True),
        sa.Column("locality", sa.String(length=100), nullable=True),
        sa.Column("legal_address", sa.String(length=500), nullable=True),
        sa.Column("caem_code", sa.String(length=10), nullable=True),
        sa.Column("activity", sa.String(length=255), nullable=True),
        sa.Column("registered_on", sa.Date(), nullable=True),
        sa.Column("client_since", sa.Date(), nullable=True),
        sa.Column(
            "client_status",
            sa.Enum(
                "onboarding",
                "active",
                name="client_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="onboarding",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("idno ~ '^[0-9]{13}$'", name=op.f("ck_clients_idno_format")),
        sa.CheckConstraint(
            "vat_code IS NULL OR (vat_payer AND vat_code ~ '^[0-9]{7}$')",
            name=op.f("ck_clients_vat_code"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_clients_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
            name=op.f("fk_clients_deleted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(
        "uq_clients_idno_active",
        "clients",
        ["idno"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "client_assignments",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_by", sa.BigInteger(), nullable=True),
        sa.Column("unassigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unassigned_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "unassigned_at IS NULL OR unassigned_at >= assigned_at",
            name=op.f("ck_client_assignments_unassigned_after"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name=op.f("fk_client_assignments_assigned_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_assignments_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unassigned_by"],
            ["users.id"],
            name=op.f("fk_client_assignments_unassigned_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_client_assignments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_assignments")),
    )
    op.create_index(
        op.f("ix_client_assignments_client_id"), "client_assignments", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_assignments_user_id"), "client_assignments", ["user_id"], unique=False
    )
    op.create_index(
        "uq_client_assignments_current",
        "client_assignments",
        ["client_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("unassigned_at IS NULL"),
    )
    op.create_table(
        "client_bank_accounts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("bank_name", sa.String(length=100), nullable=False),
        sa.Column("iban", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="MDL", nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_client_bank_accounts_currency_format")
        ),
        sa.CheckConstraint(
            "iban ~ '^MD[0-9]{2}[A-Z0-9]{20}$'", name=op.f("ck_client_bank_accounts_iban_format")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_bank_accounts_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
            name=op.f("fk_client_bank_accounts_deleted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_bank_accounts")),
    )
    op.create_index(
        op.f("ix_client_bank_accounts_client_id"),
        "client_bank_accounts",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        "uq_client_bank_accounts_iban_active",
        "client_bank_accounts",
        ["client_id", "iban"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_client_bank_accounts_primary",
        "client_bank_accounts",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("is_primary AND deleted_at IS NULL"),
    )
    op.create_table(
        "client_contacts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_contacts_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
            name=op.f("fk_client_contacts_deleted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_contacts")),
    )
    op.create_index(
        op.f("ix_client_contacts_client_id"), "client_contacts", ["client_id"], unique=False
    )
    op.create_index(
        "uq_client_contacts_primary",
        "client_contacts",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("is_primary AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_client_contacts_primary",
        table_name="client_contacts",
        postgresql_where=sa.text("is_primary AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_client_contacts_client_id"), table_name="client_contacts")
    op.drop_table("client_contacts")
    op.drop_index(
        "uq_client_bank_accounts_primary",
        table_name="client_bank_accounts",
        postgresql_where=sa.text("is_primary AND deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_client_bank_accounts_iban_active",
        table_name="client_bank_accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_client_bank_accounts_client_id"), table_name="client_bank_accounts")
    op.drop_table("client_bank_accounts")
    op.drop_index(
        "uq_client_assignments_current",
        table_name="client_assignments",
        postgresql_where=sa.text("unassigned_at IS NULL"),
    )
    op.drop_index(op.f("ix_client_assignments_user_id"), table_name="client_assignments")
    op.drop_index(op.f("ix_client_assignments_client_id"), table_name="client_assignments")
    op.drop_table("client_assignments")
    op.drop_index(
        "uq_clients_idno_active",
        table_name="clients",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("clients")
    # ### end Alembic commands ###
