"""telegram chats and link codes

Revision ID: c26312036cf8
Revises: a7c3e91d2b40
Create Date: 2026-09-27 21:04:35.549228+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c26312036cf8"
down_revision: str | None = "a7c3e91d2b40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_link_codes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_telegram_link_codes_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_telegram_link_codes_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_link_codes")),
        sa.UniqueConstraint("client_id", name=op.f("uq_telegram_link_codes_client_id")),
        sa.UniqueConstraint("code", name=op.f("uq_telegram_link_codes_code")),
    )
    op.create_table(
        "telegram_chats",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("tg_name", sa.String(length=255), nullable=True),
        sa.Column("tg_username", sa.String(length=64), nullable=True),
        sa.Column("unlinked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unlinked_by", sa.BigInteger(), nullable=True),
        sa.Column("pending_vehicle_id", sa.BigInteger(), nullable=True),
        sa.Column("pending_year", sa.Integer(), nullable=True),
        sa.Column("pending_month", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(pending_vehicle_id IS NULL) = (pending_year IS NULL) AND (pending_year IS NULL) = (pending_month IS NULL)",
            name=op.f("ck_telegram_chats_pending_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_telegram_chats_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pending_vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_telegram_chats_pending_vehicle_id_vehicles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unlinked_by"],
            ["users.id"],
            name=op.f("fk_telegram_chats_unlinked_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_chats")),
    )
    op.create_index(
        op.f("ix_telegram_chats_client_id"), "telegram_chats", ["client_id"], unique=False
    )
    op.create_index(
        "uq_telegram_chats_chat_active",
        "telegram_chats",
        ["chat_id"],
        unique=True,
        postgresql_where=sa.text("unlinked_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_telegram_chats_chat_active",
        table_name="telegram_chats",
        postgresql_where=sa.text("unlinked_at IS NULL"),
    )
    op.drop_index(op.f("ix_telegram_chats_client_id"), table_name="telegram_chats")
    op.drop_table("telegram_chats")
    op.drop_table("telegram_link_codes")
    # ### end Alembic commands ###
