"""vehicles, odometer readings, waybills

Revision ID: 4e0b8dc0dd8f
Revises: 58837756caff
Create Date: 2026-09-27 18:02:05.911300+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4e0b8dc0dd8f"
down_revision: str | None = "58837756caff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("plate", sa.String(length=15), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "benzina",
                "motorina",
                "gpl",
                "hibrid",
                name="fuel_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("fuel_norm", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("driver", sa.String(length=255), nullable=True),
        sa.Column("initial_odometer", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("plate ~ '^[A-Z0-9 -]{2,15}$'", name=op.f("ck_vehicles_plate_format")),
        sa.CheckConstraint("fuel_norm > 0", name=op.f("ck_vehicles_fuel_norm_positive")),
        sa.CheckConstraint(
            "initial_odometer >= 0", name=op.f("ck_vehicles_initial_odometer_positive")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_vehicles_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
            name=op.f("fk_vehicles_deleted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
    )
    op.create_index(op.f("ix_vehicles_client_id"), "vehicles", ["client_id"], unique=False)
    op.create_index(
        "uq_vehicles_plate_active",
        "vehicles",
        ["plate"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "odometer_readings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("vehicle_id", sa.BigInteger(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("end_odometer", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "email",
                "phone",
                "telegram",
                "other",
                name="reading_source",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column("entered_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_odometer >= 0", name=op.f("ck_odometer_readings_end_odometer_positive")
        ),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name=op.f("ck_odometer_readings_month_range")),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
            name=op.f("fk_odometer_readings_entered_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_odometer_readings_vehicle_id_vehicles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odometer_readings")),
        sa.UniqueConstraint(
            "vehicle_id", "year", "month", name=op.f("uq_odometer_readings_vehicle_id_year_month")
        ),
    )
    op.create_index(
        op.f("ix_odometer_readings_vehicle_id"), "odometer_readings", ["vehicle_id"], unique=False
    )
    op.create_table(
        "waybills",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("reading_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.String(length=30), nullable=False),
        sa.Column("plate", sa.String(length=15), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "benzina",
                "motorina",
                "gpl",
                "hibrid",
                name="fuel_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("driver", sa.String(length=255), nullable=True),
        sa.Column("fuel_norm", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("start_odometer", sa.Integer(), nullable=False),
        sa.Column("end_odometer", sa.Integer(), nullable=False),
        sa.Column("fuel_liters", sa.Numeric(precision=9, scale=2), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("issued_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "end_odometer >= start_odometer", name=op.f("ck_waybills_odometer_order")
        ),
        sa.ForeignKeyConstraint(
            ["issued_by"],
            ["users.id"],
            name=op.f("fk_waybills_issued_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["odometer_readings.id"],
            name=op.f("fk_waybills_reading_id_odometer_readings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waybills")),
        sa.UniqueConstraint("number", name=op.f("uq_waybills_number")),
        sa.UniqueConstraint("reading_id", name=op.f("uq_waybills_reading_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("waybills")
    op.drop_index(op.f("ix_odometer_readings_vehicle_id"), table_name="odometer_readings")
    op.drop_table("odometer_readings")
    op.drop_index(
        "uq_vehicles_plate_active",
        table_name="vehicles",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_vehicles_client_id"), table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
