"""fleet reminders

Revision ID: cf30a185f74e
Revises: 5259e5d5b566
Create Date: 2026-09-27 21:36:14.804614+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cf30a185f74e"
down_revision: str | None = "5259e5d5b566"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fleet_reminders",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "auto_request",
                "auto_reminder",
                "manual",
                name="reminder_kind",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "sent",
                "skipped",
                "failed",
                name="reminder_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chats", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vehicles", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name=op.f("ck_fleet_reminders_month_range")),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_fleet_reminders_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_fleet_reminders_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fleet_reminders")),
    )
    op.create_index(
        op.f("ix_fleet_reminders_client_id"), "fleet_reminders", ["client_id"], unique=False
    )
    op.create_index(
        "uq_fleet_reminders_auto",
        "fleet_reminders",
        ["client_id", "year", "month", "kind"],
        unique=True,
        postgresql_where=sa.text("kind <> 'manual'"),
    )
    op.add_column(
        "telegram_bot",
        sa.Column("auto_reminders", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_bot", "auto_reminders")
    op.drop_index(
        "uq_fleet_reminders_auto",
        table_name="fleet_reminders",
        postgresql_where=sa.text("kind <> 'manual'"),
    )
    op.drop_index(op.f("ix_fleet_reminders_client_id"), table_name="fleet_reminders")
    op.drop_table("fleet_reminders")
    # ### end Alembic commands ###
