"""reminder sending window

Revision ID: c094875556dc
Revises: cf30a185f74e
Create Date: 2026-09-27 21:45:04.108033+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c094875556dc"
down_revision: str | None = "cf30a185f74e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_bot",
        sa.Column(
            "reminder_weekdays",
            postgresql.ARRAY(sa.SmallInteger()),
            server_default=sa.text("'{1,2,3,4,5}'"),
            nullable=False,
        ),
    )
    op.add_column(
        "telegram_bot",
        sa.Column("reminder_from", sa.Time(), server_default=sa.text("'09:00'"), nullable=False),
    )
    op.add_column(
        "telegram_bot",
        sa.Column("reminder_to", sa.Time(), server_default=sa.text("'18:00'"), nullable=False),
    )
    # ### end Alembic commands ###
    # Autogenerate nu detectează constrângerile CHECK.
    op.create_check_constraint(
        op.f("ck_telegram_bot_reminder_window"), "telegram_bot", "reminder_from < reminder_to"
    )
    op.create_check_constraint(
        op.f("ck_telegram_bot_reminder_weekdays_valid"),
        "telegram_bot",
        "cardinality(reminder_weekdays) > 0 AND reminder_weekdays <@ '{1,2,3,4,5,6,7}'",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("ck_telegram_bot_reminder_weekdays_valid"), "telegram_bot", type_="check"
    )
    op.drop_constraint(op.f("ck_telegram_bot_reminder_window"), "telegram_bot", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_bot", "reminder_to")
    op.drop_column("telegram_bot", "reminder_from")
    op.drop_column("telegram_bot", "reminder_weekdays")
    # ### end Alembic commands ###
