"""report classifier

Revision ID: 4ed9d5b97bda
Revises: 75efc605cc5b
Create Date: 2026-09-27 16:17:08.100026+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4ed9d5b97bda"
down_revision: str | None = "75efc605cc5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_working", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holidays")),
        sa.UniqueConstraint("holiday_date", name=op.f("uq_holidays_holiday_date")),
    )
    op.create_table(
        "report_categories",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_report_categories_code")),
    )
    op.create_table(
        "report_periods",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum(
                "lunar",
                "trimestrial",
                "semestrial",
                "anual",
                name="period_type",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("period_no", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(period_type = 'lunar' AND period_no BETWEEN 1 AND 12) OR (period_type = 'trimestrial' AND period_no BETWEEN 1 AND 4) OR (period_type = 'semestrial' AND period_no BETWEEN 1 AND 2) OR (period_type = 'anual' AND period_no = 1)",
            name=op.f("ck_report_periods_period_no_range"),
        ),
        sa.CheckConstraint("end_date >= start_date", name=op.f("ck_report_periods_date_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_periods")),
        sa.UniqueConstraint(
            "period_type",
            "year",
            "period_no",
            name=op.f("uq_report_periods_period_type_year_period_no"),
        ),
    )
    op.create_table(
        "status_sets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_status_sets")),
        sa.UniqueConstraint("code", name=op.f("uq_status_sets_code")),
    )
    op.create_table(
        "report_types",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("legal_reference", sa.Text(), nullable=True),
        sa.Column("authority", sa.String(length=100), nullable=True),
        sa.Column(
            "periodicity",
            sa.Enum(
                "lunar",
                "trimestrial",
                "semestrial",
                "anual",
                "la_cerere",
                name="periodicity",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "deadline_rule",
            sa.Enum(
                "day_of_next_period",
                "fixed_date",
                "manual",
                name="deadline_rule",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("deadline_day", sa.Integer(), nullable=True),
        sa.Column("deadline_month", sa.Integer(), nullable=True),
        sa.Column(
            "requires_payment", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "notify_days_before",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("'{7,3,1}'"),
            nullable=False,
        ),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "deadline_rule <> 'day_of_next_period' OR deadline_day IS NOT NULL",
            name=op.f("ck_report_types_next_period_needs_day"),
        ),
        sa.CheckConstraint(
            "deadline_rule <> 'fixed_date' OR (deadline_day IS NOT NULL AND deadline_month IS NOT NULL)",
            name=op.f("ck_report_types_fixed_date_needs_day_month"),
        ),
        sa.CheckConstraint(
            "deadline_day BETWEEN 1 AND 31", name=op.f("ck_report_types_deadline_day_range")
        ),
        sa.CheckConstraint(
            "deadline_month BETWEEN 1 AND 12", name=op.f("ck_report_types_deadline_month_range")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from", name=op.f("ck_report_types_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["report_categories.id"],
            name=op.f("fk_report_types_category_id_report_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_types")),
        sa.UniqueConstraint("code", "valid_from", name=op.f("uq_report_types_code_valid_from")),
    )
    op.create_index(
        op.f("ix_report_types_category_id"), "report_types", ["category_id"], unique=False
    )
    op.create_table(
        "statuses",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("status_set_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_initial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_final", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["status_set_id"],
            ["status_sets.id"],
            name=op.f("fk_statuses_status_set_id_status_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statuses")),
        sa.UniqueConstraint("status_set_id", "code", name=op.f("uq_statuses_status_set_id_code")),
    )
    op.create_index(
        "uq_statuses_initial",
        "statuses",
        ["status_set_id"],
        unique=True,
        postgresql_where=sa.text("is_initial"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "create",
                "update",
                "delete",
                "retire",
                name="action",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "report_rules",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("report_type_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "assign",
                "exclude",
                name="action",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_type_id"],
            ["report_types.id"],
            name=op.f("fk_report_rules_report_type_id_report_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_rules")),
    )
    op.create_index(
        op.f("ix_report_rules_report_type_id"), "report_rules", ["report_type_id"], unique=False
    )
    op.create_table(
        "report_type_steps",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("report_type_id", sa.BigInteger(), nullable=False),
        sa.Column("status_set_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_type_id"],
            ["report_types.id"],
            name=op.f("fk_report_type_steps_report_type_id_report_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["status_set_id"],
            ["status_sets.id"],
            name=op.f("fk_report_type_steps_status_set_id_status_sets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_type_steps")),
        sa.UniqueConstraint(
            "report_type_id", "code", name=op.f("uq_report_type_steps_report_type_id_code")
        ),
    )
    op.create_index(
        op.f("ix_report_type_steps_status_set_id"),
        "report_type_steps",
        ["status_set_id"],
        unique=False,
    )
    op.create_table(
        "client_report_types",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("report_type_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "auto",
                "manual",
                name="source",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("valid_from", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_client_report_types_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_report_types_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_client_report_types_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_type_id"],
            ["report_types.id"],
            name=op.f("fk_client_report_types_report_type_id_report_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_report_types")),
        sa.UniqueConstraint(
            "client_id",
            "report_type_id",
            "valid_from",
            name=op.f("uq_client_report_types_client_id_report_type_id_valid_from"),
        ),
    )
    op.create_index(
        "ix_client_report_types_active",
        "client_report_types",
        ["client_id"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        op.f("ix_client_report_types_report_type_id"),
        "client_report_types",
        ["report_type_id"],
        unique=False,
    )
    op.create_table(
        "report_entries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("report_type_id", sa.BigInteger(), nullable=False),
        sa.Column("period_id", sa.BigInteger(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("assigned_user_id", sa.BigInteger(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_completed = (completed_at IS NOT NULL)",
            name=op.f("ck_report_entries_completed_at_set"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_report_entries_assigned_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_report_entries_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["report_periods.id"],
            name=op.f("fk_report_entries_period_id_report_periods"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_type_id"],
            ["report_types.id"],
            name=op.f("fk_report_entries_report_type_id_report_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_entries")),
        sa.UniqueConstraint(
            "client_id",
            "report_type_id",
            "period_id",
            name=op.f("uq_report_entries_client_id_report_type_id_period_id"),
        ),
    )
    op.create_index(
        op.f("ix_report_entries_assigned_user_id"),
        "report_entries",
        ["assigned_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_report_entries_open_deadline",
        "report_entries",
        ["deadline"],
        unique=False,
        postgresql_where=sa.text("NOT is_completed"),
    )
    op.create_index(
        op.f("ix_report_entries_period_id"), "report_entries", ["period_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_entries_report_type_id"), "report_entries", ["report_type_id"], unique=False
    )
    op.create_table(
        "report_entry_steps",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("entry_id", sa.BigInteger(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.Column("changed_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_report_entry_steps_changed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["report_entries.id"],
            name=op.f("fk_report_entry_steps_entry_id_report_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
            name=op.f("fk_report_entry_steps_status_id_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["report_type_steps.id"],
            name=op.f("fk_report_entry_steps_step_id_report_type_steps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_entry_steps")),
        sa.UniqueConstraint(
            "entry_id", "step_id", name=op.f("uq_report_entry_steps_entry_id_step_id")
        ),
    )
    op.create_index(
        op.f("ix_report_entry_steps_status_id"), "report_entry_steps", ["status_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_entry_steps_step_id"), "report_entry_steps", ["step_id"], unique=False
    )
    # Redenumire (autogenerate ar fi propus drop + add, pierzând datele).
    # PostgreSQL actualizează singur constrângerea ck_clients_vat_code.
    op.alter_column("clients", "vat_payer", new_column_name="is_vat_payer")
    op.add_column(
        "clients",
        sa.Column(
            "is_it_park_resident", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column("has_employees", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "clients",
        sa.Column("has_transport", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("clients", sa.Column("tax_regime", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "tax_regime")
    op.drop_column("clients", "has_transport")
    op.drop_column("clients", "has_employees")
    op.drop_column("clients", "is_it_park_resident")
    op.alter_column("clients", "is_vat_payer", new_column_name="vat_payer")
    op.drop_index(op.f("ix_report_entry_steps_step_id"), table_name="report_entry_steps")
    op.drop_index(op.f("ix_report_entry_steps_status_id"), table_name="report_entry_steps")
    op.drop_table("report_entry_steps")
    op.drop_index(op.f("ix_report_entries_report_type_id"), table_name="report_entries")
    op.drop_index(op.f("ix_report_entries_period_id"), table_name="report_entries")
    op.drop_index(
        "ix_report_entries_open_deadline",
        table_name="report_entries",
        postgresql_where=sa.text("NOT is_completed"),
    )
    op.drop_index(op.f("ix_report_entries_assigned_user_id"), table_name="report_entries")
    op.drop_table("report_entries")
    op.drop_index(op.f("ix_client_report_types_report_type_id"), table_name="client_report_types")
    op.drop_index(
        "ix_client_report_types_active",
        table_name="client_report_types",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("client_report_types")
    op.drop_index(op.f("ix_report_type_steps_status_set_id"), table_name="report_type_steps")
    op.drop_table("report_type_steps")
    op.drop_index(op.f("ix_report_rules_report_type_id"), table_name="report_rules")
    op.drop_table("report_rules")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(
        "uq_statuses_initial", table_name="statuses", postgresql_where=sa.text("is_initial")
    )
    op.drop_table("statuses")
    op.drop_index(op.f("ix_report_types_category_id"), table_name="report_types")
    op.drop_table("report_types")
    op.drop_table("status_sets")
    op.drop_table("report_periods")
    op.drop_table("report_categories")
    op.drop_table("holidays")
    # ### end Alembic commands ###
