"""onec balances

Revision ID: 2eebc10e679c
Revises: c094875556dc
Create Date: 2026-09-27 21:58:34.290334+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2eebc10e679c"
down_revision: str | None = "c094875556dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onec_sync_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("base_name", sa.String(length=255), nullable=True),
        sa.Column("script_version", sa.String(length=32), nullable=True),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("matched", sa.Integer(), nullable=False),
        sa.Column("total_debit", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("unmatched", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onec_sync_runs")),
    )
    op.create_index(
        op.f("ix_onec_sync_runs_received_at"), "onec_sync_runs", ["received_at"], unique=False
    )
    op.create_table(
        "onec_integration",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=True),
        sa.Column("api_key_hint", sa.String(length=12), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_onec_integration_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onec_integration")),
        sa.UniqueConstraint("api_key_hash", name=op.f("uq_onec_integration_api_key_hash")),
    )
    op.create_table(
        "client_balances",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_balances_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["onec_sync_runs.id"],
            name=op.f("fk_client_balances_run_id_onec_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_balances")),
        sa.UniqueConstraint(
            "run_id", "client_id", name=op.f("uq_client_balances_run_id_client_id")
        ),
    )
    op.create_index(
        "ix_client_balances_client_run", "client_balances", ["client_id", "run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_client_balances_client_run", table_name="client_balances")
    op.drop_table("client_balances")
    op.drop_table("onec_integration")
    op.drop_index(op.f("ix_onec_sync_runs_received_at"), table_name="onec_sync_runs")
    op.drop_table("onec_sync_runs")
    # ### end Alembic commands ###
