"""report_types.deadline_month_offset

Revision ID: 574e157aaf6d
Revises: 4ed9d5b97bda
Create Date: 2026-09-27 16:23:05.457557+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "574e157aaf6d"
down_revision: str | None = "4ed9d5b97bda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_types",
        sa.Column(
            "deadline_month_offset", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
    )
    # ### end Alembic commands ###
    # Autogenerate nu detectează constrângerile CHECK.
    op.create_check_constraint(
        op.f("ck_report_types_deadline_month_offset_range"),
        "report_types",
        "deadline_month_offset BETWEEN 0 AND 24",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("ck_report_types_deadline_month_offset_range"), "report_types", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_types", "deadline_month_offset")
    # ### end Alembic commands ###
