"""telegram bot settings

Revision ID: 5259e5d5b566
Revises: c26312036cf8
Create Date: 2026-09-27 21:15:37.503370+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5259e5d5b566"
down_revision: str | None = "c26312036cf8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_bot",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("token_encrypted", sa.Text(), nullable=True),
        sa.Column("token_hint", sa.String(length=8), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "not_configured",
                "pending",
                "connected",
                "error",
                name="bot_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="not_configured",
            nullable=False,
        ),
        sa.Column("status_message", sa.String(length=255), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_telegram_bot_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_bot")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_bot")
    # ### end Alembic commands ###
